dist: xenial
language: node_js
node_js:
    - "v12.6.0"
cache:
    yarn: true
script:
    - yarn build
    - yarn lint
    - yarn typecheck
    - yarn test:ci

# Only build PRs and master
# https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
branches:
    only:
        - master
        - /^greenkeeper.*$/

before_deploy: yarn build:docs
deploy:
    provider: pages
    local_dir: "./portal/public"
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master

notifications:
    slack:
        rooms:
            - fremtinddesignsystem:DSQEoGKwU1ypcM0CojIOygXV
        on_pull_requests: false
