language: node_js
node_js:
    - "--lts"
cache:
    yarn: true
script:
    - yarn build
    - yarn build:docs
    - yarn lint
    - yarn typecheck
    - yarn test:ci
branch: master
deploy:
    provider: pages
    local_dir: "./portal/public"
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
