language: node_js
node_js:
    - "--lts"
cache:
    directories:
        - "node_modules"
        - "build"
script:
    - yarn
    - yarn setup
    - yarn build:docs
    - yarn lint:ts
    - yarn test:ci
branch: master
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
