version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12.x
    pre_build:
        commands:
            - yarn install --frozen-lockfile
    build:
        commands:
            - |
                export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
                if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
                    export CODEBUILD_GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
                fi
                export CODEBUILD_GIT_CLEAN_BRANCH="$(echo $CODEBUILD_GIT_BRANCH | tr '/' '-')"
            - yarn build
            - GATSBY_PATH_PREFIX=$CODEBUILD_GIT_CLEAN_BRANCH yarn build:docs -- -- --prefix-paths=true
            - sh ./deploy.sh
cache:
    paths:
        - "./node_modules/**/*"
