name: release-portal
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        name: Deploy portal
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build and Deploy
              if: "!contains(github.event.head_commit.message, '[ci skip release]')"
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: portal/public
                  BUILD_SCRIPT: yarn install --frozen-lockfile && yarn build && yarn build:docs
