name: release canary

on:
    push:
        branches:
            - release/canary

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  ref: release/canary
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
                  registry-url: "https://registry.npmjs.org"
            - name: publish @canary
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
              run: |
                  git config user.email "leiv.fredrik.berge@fremtind.no"
                  git config user.name "lfbergee"
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/fremtind/jokul.git
                  yarn
                  yarn release --yes
