name: release canary

on:
    push:
        branches:
            - release/canary

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  ref: release/canary
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
                  registry-url: "https://registry.npmjs.org"
            - name: publish @canary
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
              if: "!contains(github.event.head_commit.message, '[ci skip]')"
              run: |
                  echo ${{ github.event.head_commit.message }}
