name: CI

on:
    push:
        branches:
            - "*"
            - "!master"

jobs:
    build:
        name: "Build, lint, typecheck and test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Lint and test
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn ci:test
