name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Lint and test
      run: |
        yarn
        yarn lint
        yarn test
